thrush:
  url:
    initUrl: https://kyfw.12306.cn/otn/login/init
    loginCaptcha: https://kyfw.12306.cn/passport/captcha/captcha-image?login_site=E&module=login&rand=sjrand
    auth: https://kyfw.12306.cn/passport/web/auth/uamtk
    checkCode: https://kyfw.12306.cn/passport/captcha/captcha-check
    loginUrl: https://kyfw.12306.cn/passport/web/login
  user:
    username: username
    password: password