spring:
  thymeleaf:
    cache: false
thrush:
  url:
    initUrl: https://kyfw.12306.cn/otn/login/init
    loginCaptcha: https://kyfw.12306.cn/passport/captcha/captcha-image?login_site=E&module=login&rand=sjrand
    refreshLoginCaptcha: https://kyfw.12306.cn/passport/captcha/captcha-image?login_site=E&module=login&rand=sjrand
    auth: https://kyfw.12306.cn/passport/web/auth/uamtk
    checkCode: https://kyfw.12306.cn/passport/captcha/captcha-check
    loginUrl: https://kyfw.12306.cn/passport/web/login
    uamtk: https://kyfw.12306.cn/passport/web/auth/uamtk
  user:
    username: username
    password: password
  image:
    imageLocation: /Users/eddy/Desktop/12306
    url: http://10.2.114.95:8081
  ding:
    url: https://oapi.dingtalk.com/robot/send?access_token=
    token: 9048bea05b7f10ac4fb28445397554d8232611e03cf7c872b9cdc7526a1522fe
    notifyToken: cdfea81c7b8bfa12f8e89d94b47ab85f2b5d1a617980e6dd55a33ffc4ae20ae0
  host:
    domain: http://10.2.114.95:8080
